from django.contrib.sitemaps import Sitemap
from django.shortcuts import reverse


class StaticViewSitemap(Sitemap):
    # priority = 0.5
    # changefreq = 'daily'
    def items(self):
        urls = []
        urls += ['siteMain:pageServices',
                 'siteMain:pageArticles',
                 'siteMain:pageArticle_1',
                 'siteMain:pageService_1',
                 'siteMain:pageServiceBordureBeton',
                 'siteMain:pageServiceBetonCire',
                 'siteMain:pageServiceDalleBeton',
                 'siteMain:pageServiceBetonDecoratif',
                 'siteMain:pageServiceBetonDesactive',
                 'siteMain:pageServiceBetonImprime',
                 'siteMain:pageServiceBitumeEnrobe',
                 'siteMain:pageServiceCoulageFondation',
                 'siteMain:pageServicePavageDallage',
                 'siteMain:pageServiceResineEpoxy',
                 'siteMain:pageServiceGresCerame',
                 'siteMain:pageServicePierreNaturelle',
                 'siteMain:mentions_lega',
                 'siteMain:politique_conf',
                 'siteMain:politique_cook',
                 'siteMain:thankYou',
                 ]

        urls += ['poitiers:indexPoitiers',
                 'poitiers:pageServices',
                 'poitiers:pageArticles',
                 'poitiers:pageArticle_1',
                 'poitiers:pageService_1',
                 'poitiers:pageServiceBordureBeton',
                 'poitiers:pageServiceBetonCire',
                 'poitiers:pageServiceDalleBeton',
                 'poitiers:pageServiceBetonDecoratif',
                 'poitiers:pageServiceBetonDesactive',
                 'poitiers:pageServiceBetonImprime',
                 'poitiers:pageServiceBitumeEnrobe',
                 'poitiers:pageServiceCoulageFondation',
                 'poitiers:pageServicePavageDallage',
                 'poitiers:pageServiceResineEpoxy',
                 'poitiers:pageServiceGresCerame',
                 'poitiers:pageServicePierreNaturelle',
                 'poitiers:thankYouPoitiers',
                 'poitiers:mentions_lega',
                 'poitiers:politique_cook',
                 'poitiers:politique_conf',
                 ]

        urls += ['cholet:indexCholet',
                 'cholet:pageServices',
                 'cholet:pageArticles',
                 'cholet:pageArticle_1',
                 'cholet:pageService_1',
                 'cholet:pageServiceBordureBeton',
                 'cholet:pageServiceBetonCire',
                 'cholet:pageServiceDalleBeton',
                 'cholet:pageServiceBetonDecoratif',
                 'cholet:pageServiceBetonDesactive',
                 'cholet:pageServiceBetonImprime',
                 'cholet:pageServiceBitumeEnrobe',
                 'cholet:pageServiceCoulageFondation',
                 'cholet:pageServicePavageDallage',
                 'cholet:pageServiceResineEpoxy',
                 'cholet:pageServiceGresCerame',
                 'cholet:pageServicePierreNaturelle',
                 'cholet:thankYouCholet',
                 'cholet:mentions_lega',
                 'cholet:politique_cook',
                 'cholet:politique_conf',
                 ]

        urls += ['chatellerault:indexChatellerault',
                 'chatellerault:pageServices',
                 'chatellerault:pageArticles',
                 'chatellerault:pageArticle_1',
                 'chatellerault:pageService_1',
                 'chatellerault:pageServiceBordureBeton',
                 'chatellerault:pageServiceBetonCire',
                 'chatellerault:pageServiceDalleBeton',
                 'chatellerault:pageServiceBetonDecoratif',
                 'chatellerault:pageServiceBetonDesactive',
                 'chatellerault:pageServiceBetonImprime',
                 'chatellerault:pageServiceBitumeEnrobe',
                 'chatellerault:pageServiceCoulageFondation',
                 'chatellerault:pageServicePavageDallage',
                 'chatellerault:pageServiceResineEpoxy',
                 'chatellerault:pageServiceGresCerame',
                 'chatellerault:pageServicePierreNaturelle',
                 'chatellerault:thankYouChatellerault',
                 'chatellerault:mentions_lega',
                 'chatellerault:politique_cook',
                 'chatellerault:politique_conf',
                 ]

        urls += ['antony:indexAntony',
                 'antony:pageServices',
                 'antony:pageArticles',
                 'antony:pageArticle_1',
                 'antony:pageService_1',
                 'antony:pageServiceBordureBeton',
                 'antony:pageServiceBetonCire',
                 'antony:pageServiceDalleBeton',
                 'antony:pageServiceBetonDecoratif',
                 'antony:pageServiceBetonDesactive',
                 'antony:pageServiceBetonImprime',
                 'antony:pageServiceBitumeEnrobe',
                 'antony:pageServiceCoulageFondation',
                 'antony:pageServicePavageDallage',
                 'antony:pageServiceResineEpoxy',
                 'antony:pageServiceGresCerame',
                 'antony:pageServicePierreNaturelle',
                 'antony:thankYouAntony',
                 'antony:mentions_lega',
                 'antony:politique_cook',
                 'antony:politique_conf',
                 ]

        urls += ['ales:indexAles',
                 'ales:pageServices',
                 'ales:pageArticles',
                 'ales:pageArticle_1',
                 'ales:pageService_1',
                 'ales:pageServiceBordureBeton',
                 'ales:pageServiceBetonCire',
                 'ales:pageServiceDalleBeton',
                 'ales:pageServiceBetonDecoratif',
                 'ales:pageServiceBetonDesactive',
                 'ales:pageServiceBetonImprime',
                 'ales:pageServiceBitumeEnrobe',
                 'ales:pageServiceCoulageFondation',
                 'ales:pageServicePavageDallage',
                 'ales:pageServiceResineEpoxy',
                 'ales:pageServiceGresCerame',
                 'ales:pageServicePierreNaturelle',
                 'ales:thankYouAles',
                 'ales:mentions_lega',
                 'ales:politique_cook',
                 'ales:politique_conf',
                 ]
        return urls

    def location(self, item):
        return reverse(item)

